# Generated by Django 6.0.3 on 2026-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_internship_status_alter_agreement_status_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='refusalReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
