# Generated by Django 6.0.3 on 2026-05-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('willaya', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person')], max_length=10)),
                ('maxParticipants', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('applicationDeadline', models.DateField()),
                ('internshipStartDate', models.DateField()),
                ('internshipEndDate', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.company')),
                ('requiredSkills', models.ManyToManyField(related_name='offers', to='offers.skill')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
